# Darkness benchmark. Select one level manually for each evaluation.
severity_levels: [1, 2, 3]

corruptions:
  darkness:
    levels:
      1: {factor: 0.75}
      2: {factor: 0.55}
      3: {factor: 0.35}
